# Generated by Django 5.2.13 on 2026-04-24 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Existencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedatos.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedatos.articulo')),
            ],
        ),
    ]
